sgilani12/order-tracking-blessed

- models/user.js
Added basic models/user.js file
> Add user model

- app.js
- routes/customers.js
- routes/newOrder.js
- routes/orders.js
- routes/products.js
- views/customers.ejs
- views/newOrder.ejs
- views/orders.ejs
- views/products.ejs
Merge page navigation branch into frontend
- ejs files added for main pages in views/
- routes added where necessary, updated to render pages if existing 
- generally building out frontend file structure
> Add page navigation

- models/user.js
Fixed models/user.js to better reflect the boys' database user model
> Fix user model

- config.json
- controllers/customersController.js
- package-lock.json
- package.json
packages added:
mysql2 - sequelize dependency no "require" needed
body-parser -> const bodyParser = require('body-parser')
bodyParser is initialized on app.js through app.use() functions. Have not been included yet.
> add db config new package dependencies structure of custController

- views/newOrder.ejs
- added fields for customer, product
- added link to new customer page
- order details table with functionality
- added add to drafts button (no functionality)
- submit button PUTs instead of POST for some reason
> add new order page functionality

- README.md
- app.js
- controllers/customersController.js
- controllers/ordersController.js
- routes/customers.js
- routes/newCustomer.js
integrate changes from backend team to newCustomer endpoint and routing
> Backend new customer get routes

- .gitignore
- models/customer.js
- models/order.js
- models/product.js
- models/user.js
Removed some data validators so that npm will run
> Fix models

- views/customers.ejs
- views/index.ejs
- views/orders.ejs
- views/products.ejs
- backend team updated routes and api endpoints, frontend team made the corresponding changes in the views/ files
> Update routing and endpoint to add a new customer 

- .gitignore
- models/_key.js
> Add keyfile template

- app.js
- routes/index.js
- routes/login.js
- views/logIn.ejs
routing changed to go to login page on load, then login submit button routes to the index (/dashboard)
> add login page

- controllers/customersController.js
- models/customer.js
> added getCustomersList

- InitialDiagram.drawio
- app.js
- config.json
- controllers/customersController.js
- controllers/ordersController.js
- models/_key.js
- models/customer.js
- models/order.js
- models/product.js
- models/user.js
- package-lock.json
- package.json
- routes/customers.js
- routes/orders.js
- views/customers.ejs
- views/newCustomer.ejs
- views/ordersHome.ejs
- view list of customers in a table on customers.ejs
- merged order-tracking-backend into customers-page branch prior to this PR
> Customers page

- package-lock.json
- package.json
- routes/customers.spec.js
- routes/index.spec.js
- routes/login.js
- routes/login.spec.js
- routes/newOrder.spec.js
- routes/orders.spec.js
- routes/products.spec.js
updated testing files and JSON file
> Testing one

- controllers/ordersController.js
- models/order.js
> Backend get orders

- controllers/customersController.spec.js
- controllers/ordersController.spec.js
- package-lock.json
- routes/customers.spec.js
> Added test

- views/customers.ejs
- default behavior of cancel button in js confirm() is null
- implement correct cancel/ok functionality to only make api call on CSR confirmation
> only delete if CSR confirms, make sure cancel button is functional 

- models/item.js
> added items model

- controllers/customersController.js
- controllers/ordersController.js
- controllers/productsController.js
- models/customer.js
- models/order.js
- models/product.js
- package-lock.json
- routes/orders.js
Test and merge this branch and then we need to make a pull request into develop so that frontend can start testing their new features asap
> pass customers/products to frontend to add orders + some refactoring

- public/css/global.css
- views/customers.ejs
- views/newOrder.ejs
- views/orders.ejs
- views/products.ejs
- fix merge conflicts in command line with new branch
- search functionality for all tables 
- new order form dropdown progress
> Merge izzy attempt

- views/customers.ejs
- deleting a customer was logging the CSR out
- implement workaround to not mess up authorization
> fix issue with delete customer

- package-lock.json
- public/css/global.css
- public/css/style.css
- views/customers.ejs
- views/newOrder.ejs
- views/orders.ejs
- views/partials/side-nav.ejs
- views/partials/topbar.ejs
- views/products.ejs
Should merge changes from most recent frontend work to backend dev
> Backend frontend merge
